title: Audio notebook
email: sk@samjkent.co.uk
description: Notes about Audio hardware and software
baseurl: "/audio" # the subpath of your site, e.g. /blog
url: "https://samjkent.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  samjkent

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
defaults:
  - scope:
      path: "assets"
    values:
      image: true
